import type { Entity, GraphEdge, GraphNode } from './types'

export const graphNodes: GraphNode[] = [
  { id: 'CHEBI:15377', label: 'Geranylgeranyl diphosphate', shortLabel: 'GGPP', kind: 'compound', x: 16, y: 52, tone: 'teal', meta: 'CHEBI:15377' },
  { id: 'CHEBI:17115', label: 'Geranyl diphosphate', shortLabel: 'GPP', kind: 'compound', x: 16, y: 22, tone: 'teal', meta: 'CHEBI:17115' },
  { id: 'CHEBI:17292', label: 'Farnesyl diphosphate', shortLabel: 'FPP', kind: 'compound', x: 16, y: 82, tone: 'teal', meta: 'CHEBI:17292' },
  { id: 'ENZ:Q9ZSY2', label: 'Linalool synthase', shortLabel: 'LIS', kind: 'enzyme', x: 46, y: 22, tone: 'amber', meta: 'EC 4.2.3.26' },
  { id: 'ENZ:Q5T7B8', label: 'Germacrene A synthase', shortLabel: 'GAS', kind: 'enzyme', x: 46, y: 50, tone: 'amber', meta: 'EC 4.2.3.23' },
  { id: 'ENZ:Q9FJA2', label: 'Taxadiene synthase', shortLabel: 'TXS', kind: 'enzyme', x: 46, y: 80, tone: 'amber', meta: 'EC 4.2.3.18' },
  { id: 'CHEBI:16486', label: 'Linalool', shortLabel: 'Linalool', kind: 'compound', x: 80, y: 17, tone: 'coral', meta: 'CHEBI:17579' },
  { id: 'CHEBI:17579', label: 'Germacrene A', shortLabel: 'Germacrene A', kind: 'compound', x: 80, y: 48, tone: 'coral', meta: 'CHEBI:17579' },
  { id: 'CHEBI:33998', label: 'Taxa-4,11-diene', shortLabel: 'Taxadiene', kind: 'compound', x: 80, y: 80, tone: 'coral', meta: 'CHEBI:33998' },
  { id: 'CHEBI:17347', label: 'Alpha-pinene', shortLabel: 'α-Pinene', kind: 'compound', x: 77, y: 63, tone: 'coral', meta: 'CHEBI:15356' },
]

export const graphEdges: GraphEdge[] = [
  { id: 'EDGE-001', source: 'CHEBI:17115', target: 'ENZ:Q9ZSY2', label: 'RHEA:24464', reactionId: 'RHEA:24464', enzymeId: 'ENZ:Q9ZSY2', edgeGroupId: 'GROUP-GPP' },
  { id: 'EDGE-002', source: 'ENZ:Q9ZSY2', target: 'CHEBI:16486', label: 'RHEA:24464', reactionId: 'RHEA:24464', enzymeId: 'ENZ:Q9ZSY2', edgeGroupId: 'GROUP-GPP' },
  { id: 'EDGE-003', source: 'CHEBI:17292', target: 'ENZ:Q5T7B8', label: 'RHEA:23808', reactionId: 'RHEA:23808', enzymeId: 'ENZ:Q5T7B8', edgeGroupId: 'GROUP-FPP' },
  { id: 'EDGE-004', source: 'ENZ:Q5T7B8', target: 'CHEBI:17579', label: 'RHEA:23808', reactionId: 'RHEA:23808', enzymeId: 'ENZ:Q5T7B8', edgeGroupId: 'GROUP-FPP' },
  { id: 'EDGE-005', source: 'CHEBI:15377', target: 'ENZ:Q9FJA2', label: 'RHEA:18797', reactionId: 'RHEA:18797', enzymeId: 'ENZ:Q9FJA2', edgeGroupId: 'GROUP-GGPP' },
  { id: 'EDGE-006', source: 'ENZ:Q9FJA2', target: 'CHEBI:33998', label: 'RHEA:18797', reactionId: 'RHEA:18797', enzymeId: 'ENZ:Q9FJA2', edgeGroupId: 'GROUP-GGPP' },
  { id: 'EDGE-007', source: 'CHEBI:17292', target: 'ENZ:Q5T7B8', label: 'RHEA:23809', reactionId: 'RHEA:23809', enzymeId: 'ENZ:Q5T7B8', edgeGroupId: 'GROUP-FPP', curved: true },
  { id: 'EDGE-008', source: 'ENZ:Q5T7B8', target: 'CHEBI:17347', label: 'RHEA:23809', reactionId: 'RHEA:23809', enzymeId: 'ENZ:Q5T7B8', edgeGroupId: 'GROUP-FPP', curved: true },
]

export const entities: Entity[] = [
  {
    id: 'CHEBI:15377',
    kind: 'compound',
    name: 'Geranylgeranyl diphosphate',
    subtitle: 'GGPP · CHEBI:15377',
    description: 'A diterpenoid precursor that sits upstream of several plant terpene biosynthesis routes.',
    tags: ['Diterpene precursor', 'Substrate'],
    imageLabel: '2D structure preview',
    species: 'Taxus baccata',
    compoundClass: 'Diterpene',
    fields: [{ label: 'Formula', value: 'C20H33O7P2' }, { label: 'Molecular weight', value: '454.43 g/mol' }, { label: 'Class', value: 'Prenol lipid' }, { label: 'Source count', value: '18 species' }],
    related: [{ id: 'ENZ:Q9FJA2', name: 'Taxadiene synthase', kind: 'enzyme' }, { id: 'CHEBI:33998', name: 'Taxa-4,11-diene', kind: 'compound' }],
  },
  {
    id: 'CHEBI:17115',
    kind: 'compound',
    name: 'Geranyl diphosphate',
    subtitle: 'GPP · CHEBI:17115',
    description: 'A monoterpene precursor used by linalool synthases and related cyclases.',
    tags: ['Monoterpene precursor', 'Substrate'],
    imageLabel: '2D structure preview',
    species: 'Arabidopsis thaliana',
    compoundClass: 'Monoterpene',
    fields: [{ label: 'Formula', value: 'C10H19O7P2' }, { label: 'Molecular weight', value: '312.19 g/mol' }, { label: 'Class', value: 'Prenol lipid' }, { label: 'Source count', value: '12 species' }],
    related: [{ id: 'ENZ:Q9ZSY2', name: 'Linalool synthase', kind: 'enzyme' }, { id: 'CHEBI:16486', name: 'Linalool', kind: 'compound' }],
  },
  {
    id: 'CHEBI:16486',
    kind: 'compound',
    name: 'Linalool',
    subtitle: 'Linalool · CHEBI:16486',
    description: 'An acyclic monoterpene alcohol found in the product profile of multiple plant TPS enzymes.',
    tags: ['Monoterpene', 'Product'],
    imageLabel: '2D structure preview',
    species: 'Arabidopsis thaliana',
    compoundClass: 'Monoterpene',
    fields: [{ label: 'Formula', value: 'C10H18O' }, { label: 'Molecular weight', value: '154.25 g/mol' }, { label: 'CAS', value: '78-70-6' }, { label: 'Source count', value: '26 species' }],
    related: [{ id: 'ENZ:Q9ZSY2', name: 'Linalool synthase', kind: 'enzyme' }, { id: 'CHEBI:17115', name: 'Geranyl diphosphate', kind: 'compound' }],
  },
  {
    id: 'CHEBI:17579',
    kind: 'compound',
    name: 'Germacrene A',
    subtitle: 'Germacrene A · CHEBI:17579',
    description: 'A sesquiterpene product linked to the FPP branch in the curated terpene network.',
    tags: ['Sesquiterpene', 'Product'],
    imageLabel: '2D structure preview',
    species: 'Cichorium intybus',
    compoundClass: 'Sesquiterpene',
    fields: [{ label: 'Formula', value: 'C15H24' }, { label: 'Molecular weight', value: '204.36 g/mol' }, { label: 'Class', value: 'Sesquiterpene' }, { label: 'Source count', value: '9 species' }],
    related: [{ id: 'ENZ:Q5T7B8', name: 'Germacrene A synthase', kind: 'enzyme' }, { id: 'CHEBI:17292', name: 'Farnesyl diphosphate', kind: 'compound' }],
  },
  {
    id: 'CHEBI:33998',
    kind: 'compound',
    name: 'Taxa-4,11-diene',
    subtitle: 'Taxadiene · CHEBI:33998',
    description: 'The committed diterpene intermediate for taxol biosynthesis studies.',
    tags: ['Diterpene', 'Product'],
    imageLabel: '2D structure preview',
    species: 'Taxus baccata',
    compoundClass: 'Diterpene',
    fields: [{ label: 'Formula', value: 'C20H32' }, { label: 'Molecular weight', value: '272.47 g/mol' }, { label: 'Class', value: 'Taxane' }, { label: 'Source count', value: '4 species' }],
    related: [{ id: 'ENZ:Q9FJA2', name: 'Taxadiene synthase', kind: 'enzyme' }, { id: 'CHEBI:15377', name: 'Geranylgeranyl diphosphate', kind: 'compound' }],
  },
  {
    id: 'ENZ:Q9ZSY2',
    kind: 'enzyme',
    name: 'Linalool synthase',
    subtitle: 'Q9ZSY2 · EC 4.2.3.26',
    description: 'A terpene synthase that converts geranyl diphosphate into linalool in the curated reference set.',
    tags: ['TPS-b', 'Monoterpene synthase'],
    species: 'Arabidopsis thaliana',
    enzymeFamily: 'TPS-b',
    fields: [{ label: 'UniProt', value: 'Q9ZSY2' }, { label: 'EC number', value: '4.2.3.26' }, { label: 'Organism', value: 'Arabidopsis thaliana' }, { label: 'Gene name', value: 'AtTPS4' }, { label: 'Sequence length', value: '585 aa' }],
    related: [{ id: 'CHEBI:17115', name: 'Geranyl diphosphate', kind: 'compound' }, { id: 'CHEBI:16486', name: 'Linalool', kind: 'compound' }],
  },
  {
    id: 'ENZ:Q5T7B8',
    kind: 'enzyme',
    name: 'Germacrene A synthase',
    subtitle: 'Q5T7B8 · EC 4.2.3.23',
    description: 'A sesquiterpene synthase with multiple curated products in the FPP branch.',
    tags: ['TPS-a', 'Sesquiterpene synthase'],
    species: 'Cichorium intybus',
    enzymeFamily: 'TPS-a',
    fields: [{ label: 'UniProt', value: 'Q5T7B8' }, { label: 'EC number', value: '4.2.3.23' }, { label: 'Organism', value: 'Cichorium intybus' }, { label: 'Gene name', value: 'CdTPS1' }, { label: 'Sequence length', value: '579 aa' }],
    related: [{ id: 'CHEBI:17292', name: 'Farnesyl diphosphate', kind: 'compound' }, { id: 'CHEBI:17579', name: 'Germacrene A', kind: 'compound' }, { id: 'CHEBI:17347', name: 'Alpha-pinene', kind: 'compound' }],
  },
  {
    id: 'ENZ:Q9FJA2',
    kind: 'enzyme',
    name: 'Taxadiene synthase',
    subtitle: 'Q9FJA2 · EC 4.2.3.18',
    description: 'A diterpene synthase responsible for the first committed step toward taxane scaffolds.',
    tags: ['TPS-d', 'Diterpene synthase'],
    species: 'Taxus baccata',
    enzymeFamily: 'TPS-d',
    fields: [{ label: 'UniProt', value: 'Q9FJA2' }, { label: 'EC number', value: '4.2.3.18' }, { label: 'Organism', value: 'Taxus baccata' }, { label: 'Gene name', value: 'TXS' }, { label: 'Sequence length', value: '862 aa' }],
    related: [{ id: 'CHEBI:15377', name: 'Geranylgeranyl diphosphate', kind: 'compound' }, { id: 'CHEBI:33998', name: 'Taxa-4,11-diene', kind: 'compound' }],
  },
  {
    id: 'RHEA:24464',
    kind: 'reaction',
    name: 'Geranyl diphosphate cyclization',
    subtitle: 'RHEA:24464 · EC 4.2.3.26',
    description: 'The curated reaction connecting GPP to the linalool product branch.',
    tags: ['Monoterpene route', 'Curated reaction'],
    imageLabel: 'Atom map preview',
    species: 'Arabidopsis thaliana',
    enzymeFamily: 'TPS-b',
    fields: [{ label: 'Rhea ID', value: 'RHEA:24464' }, { label: 'Direction', value: 'GPP → Linalool' }, { label: 'Catalyst count', value: '3 enzymes' }, { label: 'Evidence', value: 'Reviewed' }],
    related: [{ id: 'CHEBI:17115', name: 'Geranyl diphosphate', kind: 'compound' }, { id: 'ENZ:Q9ZSY2', name: 'Linalool synthase', kind: 'enzyme' }],
  },
]

export const filterOptions = {
  species: ['All species', 'Arabidopsis thaliana', 'Cichorium intybus', 'Taxus baccata'],
  classes: ['All compound classes', 'Monoterpene', 'Sesquiterpene', 'Diterpene'],
  families: ['All enzyme families', 'TPS-a', 'TPS-b', 'TPS-d'],
}

export const getEntity = (id: string) => entities.find((entity) => entity.id === id)
